# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - streetsupport-platform-api

on:
  push:
    branches:
      - staging     # Deploys to staging slot
      - main        # Deploys to production slot
      
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ENV: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup Sentry
        run: |
          npm install -g @sentry/cli
          sentry-cli --auth-token $SENTRY_AUTH_TOKEN info
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Update to 'Production' || 'Staging' when configure additional environment
    environment: ${{ github.ref_name == 'main' && 'Staging' || 'Staging' }}
    permissions:
      id-token: write # Required for OIDC
      contents: read  # Required for actions/checkout


    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App Slot'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          # Current: Using slots in a single web app
          app-name: ${{ secrets.AZURE_APP_NAME }}
          # slot-name: ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}
          
          # Alternative: For separate web apps (uncomment and modify as needed)
          # app-name: ${{ github.ref_name == 'main' && 'streetsupport-platform-api' || 'streetsupport-platform-api-staging' }}
          # Remove or comment out slot-name when using separate apps
          package: .
